site_name: 貝氏統計 300 則 bayes300

nav:
  - About: about.md
  - Notes:
    - index.md
    - polya_gamma.ipynb
  #- Blog:
  #  - blog/index.md
    

theme: 
  name: readthedocs
  user_color_mode_toggle: true
  features:
    - navigation.sections
 

markdown_extensions:
  - footnotes # 支持脚注
  - admonition # 支持提示块
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



plugins:
  - search
  #- blog
  - mkdocs-jupyter
  #- mknotebooks:
  #    enable_default_jupyter_cell_styling: true
  #    enable_default_pandas_dataframe_styling: true

